select snid,gameid	,
				payment_amount,
				pay_rate	,
				dau	,
				install	,
				dnu	,
				if(arpu is null or arpu='NaN',0,arpu) as arpu,	
				if(arppu is null or arppu='NaN',0,arppu) as arppu,
				payer as	pu,				
				payment_cnt	,
				if(gunfu_amount is null,0,round(gunfu_amount,2) ) as roll_amount,
				if(gunfu_user is null,0,gunfu_user)	as	roll_users	,
				if(gunfu_payer is null,0,gunfu_payer)	as	roll_pay_users	,
				if(new_payer is null,0,new_payer)	as	new_pu	,
				if(new_payment is null,0,round(new_payment,2)) as new_pay_amount,
				if(install_payer is null,0,install_payer)	as	install_pu	,
				if(install_payment is null,0,round(install_payment,2)) as install_pay_amount,
				round(cast(acu as double),0)	acu	,
				avg_user_time	as	avg_user_time	,
				round(cast( pcu as double),0) as pcu,
				ds	as	day,
				role_choice
from facts.f_game_day where ds='${statDay}' ${snGameIdsSql}